In [1]:
import pandas as pd
import polars as pl

In [2]:
pl.__version__

'1.7.0'

In [13]:
url = 'https://raw.githubusercontent.com/mattharrison/2023-Pycon-Polars/main/__mharrison__2020-2021.csv'
df = pl.read_csv(url)
df

shape: (5_791, 40)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Tweet id  ┆ Tweet     ┆ Tweet     ┆ time      ┆ … ┆ promoted  ┆ promoted  ┆ promoted  ┆ promoted │
│ ---       ┆ permalink ┆ text      ┆ ---       ┆   ┆ email     ┆ dial      ┆ media     ┆ media    │
│ i64       ┆ ---       ┆ ---       ┆ str       ┆   ┆ tweet     ┆ phone     ┆ views     ┆ engageme │
│           ┆ str       ┆ str       ┆           ┆   ┆ ---       ┆ ---       ┆ ---       ┆ nts      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 121258051 ┆ https://t ┆ Sounds    ┆ 2020-01-0 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 790578073 ┆ witter.co ┆ like a    ┆ 2 03:44:0 ┆   ┆           ┆           ┆           ┆          │
│ 7         ┆ m/__mharr ┆ great     ┆ 0+00:00   ┆   ┆           ┆           ┆           ┆          │
│           ┆ iso…      ┆ topic!    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ htt…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 121258249 ┆ https://t ┆ @FogleBir ┆ 2020-01-0 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 482803609 ┆ witter.co ┆ d Looks   ┆ 2 03:52:0 ┆   ┆           ┆           ┆           ┆          │
│ 7         ┆ m/__mharr ┆ like SLC. ┆ 0+00:00   ┆   ┆           ┆           ┆           ┆          │
│           ┆ iso…      ┆ I c…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 121261373 ┆ https://t ┆ @afilina  ┆ 2020-01-0 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 569869004 ┆ witter.co ┆ That's    ┆ 2 05:56:0 ┆   ┆           ┆           ┆           ┆          │
│ 9         ┆ m/__mharr ┆ really    ┆ 0+00:00   ┆   ┆           ┆           ┆           ┆          │
│           ┆ iso…      ┆ amount …  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 121291174 ┆ https://t ┆ @randal_o ┆ 2020-01-0 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 961724211 ┆ witter.co ┆ lson I    ┆ 3 01:41:0 ┆   ┆           ┆           ┆           ┆          │
│ 3         ┆ m/__mharr ┆ use       ┆ 0+00:00   ┆   ┆           ┆           ┆           ┆          │
│           ┆ iso…      ┆ anaconda  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ w…        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 121292055 ┆ https://t ┆ @AlSweiga ┆ 2020-01-0 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 602825216 ┆ witter.co ┆ rt        ┆ 3 02:16:0 ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆ m/__mharr ┆ Sometimes ┆ 0+00:00   ┆   ┆           ┆           ┆           ┆          │
│           ┆ iso…      ┆ the stud… ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 147530066 ┆ https://t ┆ @allison_ ┆ 2021-12-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 185193472 ┆ witter.co ┆ horst     ┆ 7 03:01:0 ┆   ┆           ┆           ┆           ┆          │
│ 1         ┆ m/__mharr ┆ That's    ┆ 0+00:00   ┆   ┆           ┆           ┆           ┆          │
│           ┆ iso…      ┆ awesome!  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 147551814 ┆ https://t ┆ @willmcgu ┆ 2021-12-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 369080115 ┆ witter.co ┆ gan You   ┆ 7 17:25:0 ┆   ┆           ┆           ┆           ┆          │
│ 6         ┆ m/__mharr ┆ need to   ┆ 0+00:00   ┆   ┆           ┆           ┆           ┆          │
│           ┆ iso…      ┆ find …    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 147589144 ┆ https://t ┆ @posco    ┆ 2021-12-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 124302540 ┆ witter.co ┆ Visiting  ┆ 8 18:08:0 ┆   ┆           ┆           ┆           ┆          │
│ 8         ┆ m/__mharr ┆ Hawaii    ┆ 0+00:00   ┆   ┆           ┆           ┆           ┆          │
│           ┆ iso…      ┆ for the…  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 147645381 ┆ https://t ┆ @johndsau ┆ 2021-12-3 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 975187865 ┆ witter.co ┆ nders My  ┆ 0 07:23:0 ┆   ┆           ┆           ┆           ┆          │
│ 6         ┆ m/__mharr ┆ son just  ┆ 0+00:00   ┆   ┆           ┆           ┆           ┆          │
│           ┆ iso…      ┆ bui…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 147702472 ┆ https://t ┆ @tunguz   ┆ 2021-12-3 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 205115801 ┆ witter.co ┆ Xgboost   ┆ 1 21:11:0 ┆   ┆           ┆           ┆           ┆          │
│ 8         ┆ m/__mharr ┆           ┆ 0+00:00   ┆   ┆           ┆           ┆           ┆          │
│           ┆ iso…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [16]:
print(len(dir(pl)))

200

In [17]:
df.sample(20).transpose()

shape: (40, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ column_0  ┆ column_1  ┆ column_2  ┆ column_3  ┆ … ┆ column_16 ┆ column_17 ┆ column_18 ┆ column_1 │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ 9        │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 137330697 ┆ 133474261 ┆ 145954590 ┆ 146857251 ┆ … ┆ 129101387 ┆ 134632483 ┆ 128350651 ┆ 14383573 │
│ 479687372 ┆ 167691777 ┆ 112332595 ┆ 502688666 ┆   ┆ 456553779 ┆ 693138739 ┆ 637749760 ┆ 09613248 │
│ 9         ┆ 0         ┆ 5         ┆ 8         ┆   ┆ 2         ┆ 4         ┆ 1         ┆ 519      │
│ https://t ┆ https://t ┆ https://t ┆ https://t ┆ … ┆ https://t ┆ https://t ┆ https://t ┆ https:// │
│ witter.co ┆ witter.co ┆ witter.co ┆ witter.co ┆   ┆ witter.co ┆ witter.co ┆ witter.co ┆ twitter. │
│ m/__mharr ┆ m/__mharr ┆ m/__mharr ┆ m/__mharr ┆   ┆ m/__mharr ┆ m/__mharr ┆ m/__mharr ┆ com/__mh │
│ iso…      ┆ iso…      ┆ iso…      ┆ iso…      ┆   ┆ iso…      ┆ iso…      ┆ iso…      ┆ arriso…  │
│ @naveenk0 ┆ @chrisalb ┆ @f_s_mart ┆ @gusthema ┆ … ┆ @walkingr ┆ @bryce    ┆ This is   ┆ @sarahca │
│ ta Yes,   ┆ on Just   ┆ ins Yes.  ┆ Certainly ┆   ┆ iver      ┆ Why not   ┆ why       ┆ t21 So   │
│ smooth    ┆ bought a  ┆ It flies  ┆ easier to ┆   ┆ Would     ┆ spread    ┆ corporate ┆ five     │
│ talker…   ┆ 9 in…     ┆ ver…      ┆ …         ┆   ┆ love to   ┆ the love… ┆ training… ┆ years    │
│           ┆           ┆           ┆           ┆   ┆ se…       ┆           ┆           ┆ out?…    │
│ 2021-03-2 ┆ 2020-12-0 ┆ 2021-11-1 ┆ 2021-12-0 ┆ … ┆ 2020-08-0 ┆ 2021-01-0 ┆ 2020-07-1 ┆ 2021-09- │
│ 0 16:14:0 ┆ 4 06:13:0 ┆ 3 15:37:0 ┆ 8 13:25:0 ┆   ┆ 5 14:11:0 ┆ 5 05:17:0 ┆ 5 20:59:0 ┆ 16 04:21 │
│ 0+00:00   ┆ 0+00:00   ┆ 0+00:00   ┆ 0+00:00   ┆   ┆ 0+00:00   ┆ 0+00:00   ┆ 0+00:00   ┆ :00+00:0 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ 12.0      ┆ 1622.0    ┆ 73.0      ┆ 124.0     ┆ … ┆ 381.0     ┆ 342.0     ┆ 1108.0    ┆ 1358.0   │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [18]:
df.dtypes

[Int64,
 String,
 String,
 String,
 Float64,
 Float64,
 Float64,
 Float64,
 Float64,
 Float64,
 Float64,
 Float64,
 Float64,
 Float64,
 Float64,
 Int64,
 Int64,
 Int64,
 Int64,
 Int64,
 Int64,
 Int64,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String]