In [1]:
import pandas as pd
import pandas_datareader.data as web

In [23]:
url = 'https://raw.githubusercontent.com/mattharrison/datasets/master/data/dirtydevil.txt'
df = pd.read_csv(url, sep='\t', skiprows = lambda num: num <34 or num == 35)    
df.head()

/var/folders/pg/zck9hy351gbfrqfqp_z4gb1m0000gn/T/ipykernel_10178/1051568417.py:2: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url, sep='\t', skiprows = lambda num: num <34 or num == 35)

,agency_cd,site_no,datetime,tz_cd,144166_00060,144166_00060_cd,144167_00065,144167_00065_cd
0,USGS,9333500,2001-05-07 01:00,MDT,71.0,A:[91],NaN,NaN
1,USGS,9333500,2001-05-07 01:15,MDT,71.0,A:[91],NaN,NaN
2,USGS,9333500,2001-05-07 01:30,MDT,71.0,A:[91],NaN,NaN
3,USGS,9333500,2001-05-07 01:45,MDT,70.0,A:[91],NaN,NaN
4,USGS,9333500,2001-05-07 02:00,MDT,70.0,A:[91],NaN,NaN

In [14]:
df.loc['2019'].head()

               Open     High      Low    Close        Volume
Date
2019-10-09  277.055  278.523  275.072  277.551  6.895577e+07
2019-10-08  277.333  278.096  274.913  274.953  1.065972e+08
2019-10-07  279.643  281.368  278.969  279.276  6.365530e+07
2019-10-04  277.431  280.754  277.125  280.476  6.999823e+07
2019-10-03  274.249  276.777  271.403  276.747  9.015386e+07